version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nuancce
      - POSTGRES_PASSWORD=0516
      - POSTGRES_DB=database_statistics
